// Generated by view binder compiler. Do not edit!
package com.example.itinerarybuddy.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.EditText;
import android.widget.ScrollView;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.itinerarybuddy.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class AdminDashboardActivityBinding implements ViewBinding {
  @NonNull
  private final ScrollView rootView;

  @NonNull
  public final TextView adminDashboardTitle;

  @NonNull
  public final Button confirm1;

  @NonNull
  public final Button confirm2;

  @NonNull
  public final Button confirm3;

  @NonNull
  public final Button confirm4;

  @NonNull
  public final Button confirm5;

  @NonNull
  public final Button confirm6;

  @NonNull
  public final TextView disablePosting;

  @NonNull
  public final TextView enablePosting;

  @NonNull
  public final TextView enterUserId1;

  @NonNull
  public final TextView enterUserId2;

  @NonNull
  public final TextView enterUserId3;

  @NonNull
  public final TextView enterUserId4;

  @NonNull
  public final TextView enterUserId5;

  @NonNull
  public final TextView enterUserId6;

  @NonNull
  public final TextView grantAdmin;

  @NonNull
  public final TextView grantAmbassadorStatus;

  @NonNull
  public final EditText idInput1;

  @NonNull
  public final EditText idInput2;

  @NonNull
  public final EditText idInput3;

  @NonNull
  public final EditText idInput4;

  @NonNull
  public final EditText idInput5;

  @NonNull
  public final EditText idInput6;

  @NonNull
  public final Button returnHome;

  @NonNull
  public final TextView revokeAdmin;

  @NonNull
  public final TextView revokeAmbassador;

  @NonNull
  public final View view;

  private AdminDashboardActivityBinding(@NonNull ScrollView rootView,
      @NonNull TextView adminDashboardTitle, @NonNull Button confirm1, @NonNull Button confirm2,
      @NonNull Button confirm3, @NonNull Button confirm4, @NonNull Button confirm5,
      @NonNull Button confirm6, @NonNull TextView disablePosting, @NonNull TextView enablePosting,
      @NonNull TextView enterUserId1, @NonNull TextView enterUserId2,
      @NonNull TextView enterUserId3, @NonNull TextView enterUserId4,
      @NonNull TextView enterUserId5, @NonNull TextView enterUserId6, @NonNull TextView grantAdmin,
      @NonNull TextView grantAmbassadorStatus, @NonNull EditText idInput1,
      @NonNull EditText idInput2, @NonNull EditText idInput3, @NonNull EditText idInput4,
      @NonNull EditText idInput5, @NonNull EditText idInput6, @NonNull Button returnHome,
      @NonNull TextView revokeAdmin, @NonNull TextView revokeAmbassador, @NonNull View view) {
    this.rootView = rootView;
    this.adminDashboardTitle = adminDashboardTitle;
    this.confirm1 = confirm1;
    this.confirm2 = confirm2;
    this.confirm3 = confirm3;
    this.confirm4 = confirm4;
    this.confirm5 = confirm5;
    this.confirm6 = confirm6;
    this.disablePosting = disablePosting;
    this.enablePosting = enablePosting;
    this.enterUserId1 = enterUserId1;
    this.enterUserId2 = enterUserId2;
    this.enterUserId3 = enterUserId3;
    this.enterUserId4 = enterUserId4;
    this.enterUserId5 = enterUserId5;
    this.enterUserId6 = enterUserId6;
    this.grantAdmin = grantAdmin;
    this.grantAmbassadorStatus = grantAmbassadorStatus;
    this.idInput1 = idInput1;
    this.idInput2 = idInput2;
    this.idInput3 = idInput3;
    this.idInput4 = idInput4;
    this.idInput5 = idInput5;
    this.idInput6 = idInput6;
    this.returnHome = returnHome;
    this.revokeAdmin = revokeAdmin;
    this.revokeAmbassador = revokeAmbassador;
    this.view = view;
  }

  @Override
  @NonNull
  public ScrollView getRoot() {
    return rootView;
  }

  @NonNull
  public static AdminDashboardActivityBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static AdminDashboardActivityBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.admin_dashboard_activity, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static AdminDashboardActivityBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.admin_dashboard_title;
      TextView adminDashboardTitle = ViewBindings.findChildViewById(rootView, id);
      if (adminDashboardTitle == null) {
        break missingId;
      }

      id = R.id.confirm1;
      Button confirm1 = ViewBindings.findChildViewById(rootView, id);
      if (confirm1 == null) {
        break missingId;
      }

      id = R.id.confirm2;
      Button confirm2 = ViewBindings.findChildViewById(rootView, id);
      if (confirm2 == null) {
        break missingId;
      }

      id = R.id.confirm3;
      Button confirm3 = ViewBindings.findChildViewById(rootView, id);
      if (confirm3 == null) {
        break missingId;
      }

      id = R.id.confirm4;
      Button confirm4 = ViewBindings.findChildViewById(rootView, id);
      if (confirm4 == null) {
        break missingId;
      }

      id = R.id.confirm5;
      Button confirm5 = ViewBindings.findChildViewById(rootView, id);
      if (confirm5 == null) {
        break missingId;
      }

      id = R.id.confirm6;
      Button confirm6 = ViewBindings.findChildViewById(rootView, id);
      if (confirm6 == null) {
        break missingId;
      }

      id = R.id.disable_posting;
      TextView disablePosting = ViewBindings.findChildViewById(rootView, id);
      if (disablePosting == null) {
        break missingId;
      }

      id = R.id.enable_posting;
      TextView enablePosting = ViewBindings.findChildViewById(rootView, id);
      if (enablePosting == null) {
        break missingId;
      }

      id = R.id.enter_user_id1;
      TextView enterUserId1 = ViewBindings.findChildViewById(rootView, id);
      if (enterUserId1 == null) {
        break missingId;
      }

      id = R.id.enter_user_id2;
      TextView enterUserId2 = ViewBindings.findChildViewById(rootView, id);
      if (enterUserId2 == null) {
        break missingId;
      }

      id = R.id.enter_user_id3;
      TextView enterUserId3 = ViewBindings.findChildViewById(rootView, id);
      if (enterUserId3 == null) {
        break missingId;
      }

      id = R.id.enter_user_id4;
      TextView enterUserId4 = ViewBindings.findChildViewById(rootView, id);
      if (enterUserId4 == null) {
        break missingId;
      }

      id = R.id.enter_user_id5;
      TextView enterUserId5 = ViewBindings.findChildViewById(rootView, id);
      if (enterUserId5 == null) {
        break missingId;
      }

      id = R.id.enter_user_id6;
      TextView enterUserId6 = ViewBindings.findChildViewById(rootView, id);
      if (enterUserId6 == null) {
        break missingId;
      }

      id = R.id.grant_admin;
      TextView grantAdmin = ViewBindings.findChildViewById(rootView, id);
      if (grantAdmin == null) {
        break missingId;
      }

      id = R.id.grant_ambassador_status;
      TextView grantAmbassadorStatus = ViewBindings.findChildViewById(rootView, id);
      if (grantAmbassadorStatus == null) {
        break missingId;
      }

      id = R.id.id_input1;
      EditText idInput1 = ViewBindings.findChildViewById(rootView, id);
      if (idInput1 == null) {
        break missingId;
      }

      id = R.id.id_input2;
      EditText idInput2 = ViewBindings.findChildViewById(rootView, id);
      if (idInput2 == null) {
        break missingId;
      }

      id = R.id.id_input3;
      EditText idInput3 = ViewBindings.findChildViewById(rootView, id);
      if (idInput3 == null) {
        break missingId;
      }

      id = R.id.id_input4;
      EditText idInput4 = ViewBindings.findChildViewById(rootView, id);
      if (idInput4 == null) {
        break missingId;
      }

      id = R.id.id_input5;
      EditText idInput5 = ViewBindings.findChildViewById(rootView, id);
      if (idInput5 == null) {
        break missingId;
      }

      id = R.id.id_input6;
      EditText idInput6 = ViewBindings.findChildViewById(rootView, id);
      if (idInput6 == null) {
        break missingId;
      }

      id = R.id.return_home;
      Button returnHome = ViewBindings.findChildViewById(rootView, id);
      if (returnHome == null) {
        break missingId;
      }

      id = R.id.revoke_admin;
      TextView revokeAdmin = ViewBindings.findChildViewById(rootView, id);
      if (revokeAdmin == null) {
        break missingId;
      }

      id = R.id.revoke_ambassador;
      TextView revokeAmbassador = ViewBindings.findChildViewById(rootView, id);
      if (revokeAmbassador == null) {
        break missingId;
      }

      id = R.id.view;
      View view = ViewBindings.findChildViewById(rootView, id);
      if (view == null) {
        break missingId;
      }

      return new AdminDashboardActivityBinding((ScrollView) rootView, adminDashboardTitle, confirm1,
          confirm2, confirm3, confirm4, confirm5, confirm6, disablePosting, enablePosting,
          enterUserId1, enterUserId2, enterUserId3, enterUserId4, enterUserId5, enterUserId6,
          grantAdmin, grantAmbassadorStatus, idInput1, idInput2, idInput3, idInput4, idInput5,
          idInput6, returnHome, revokeAdmin, revokeAmbassador, view);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
