// Generated by view binder compiler. Do not edit!
package com.example.itinerarybuddy.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.LinearLayout;
import android.widget.ListView;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.itinerarybuddy.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class DialogGroupDetailsBinding implements ViewBinding {
  @NonNull
  private final LinearLayout rootView;

  @NonNull
  public final TextView groupCodeLabel;

  @NonNull
  public final ListView groupMembersList;

  @NonNull
  public final TextView membersLabel;

  private DialogGroupDetailsBinding(@NonNull LinearLayout rootView,
      @NonNull TextView groupCodeLabel, @NonNull ListView groupMembersList,
      @NonNull TextView membersLabel) {
    this.rootView = rootView;
    this.groupCodeLabel = groupCodeLabel;
    this.groupMembersList = groupMembersList;
    this.membersLabel = membersLabel;
  }

  @Override
  @NonNull
  public LinearLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static DialogGroupDetailsBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static DialogGroupDetailsBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.dialog_group_details, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static DialogGroupDetailsBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.group_code_label;
      TextView groupCodeLabel = ViewBindings.findChildViewById(rootView, id);
      if (groupCodeLabel == null) {
        break missingId;
      }

      id = R.id.group_members_list;
      ListView groupMembersList = ViewBindings.findChildViewById(rootView, id);
      if (groupMembersList == null) {
        break missingId;
      }

      id = R.id.members_label;
      TextView membersLabel = ViewBindings.findChildViewById(rootView, id);
      if (membersLabel == null) {
        break missingId;
      }

      return new DialogGroupDetailsBinding((LinearLayout) rootView, groupCodeLabel,
          groupMembersList, membersLabel);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
