// Generated by view binder compiler. Do not edit!
package com.example.itinerarybuddy.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.EditText;
import android.widget.LinearLayout;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.itinerarybuddy.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class DialogAddItineraryBinding implements ViewBinding {
  @NonNull
  private final LinearLayout rootView;

  @NonNull
  public final EditText destinationEditText;

  @NonNull
  public final EditText endDateEditText;

  @NonNull
  public final EditText startDateEditText;

  private DialogAddItineraryBinding(@NonNull LinearLayout rootView,
      @NonNull EditText destinationEditText, @NonNull EditText endDateEditText,
      @NonNull EditText startDateEditText) {
    this.rootView = rootView;
    this.destinationEditText = destinationEditText;
    this.endDateEditText = endDateEditText;
    this.startDateEditText = startDateEditText;
  }

  @Override
  @NonNull
  public LinearLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static DialogAddItineraryBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static DialogAddItineraryBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.dialog_add_itinerary, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static DialogAddItineraryBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.destinationEditText;
      EditText destinationEditText = ViewBindings.findChildViewById(rootView, id);
      if (destinationEditText == null) {
        break missingId;
      }

      id = R.id.endDateEditText;
      EditText endDateEditText = ViewBindings.findChildViewById(rootView, id);
      if (endDateEditText == null) {
        break missingId;
      }

      id = R.id.startDateEditText;
      EditText startDateEditText = ViewBindings.findChildViewById(rootView, id);
      if (startDateEditText == null) {
        break missingId;
      }

      return new DialogAddItineraryBinding((LinearLayout) rootView, destinationEditText,
          endDateEditText, startDateEditText);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
