// Generated by view binder compiler. Do not edit!
package com.example.itinerarybuddy.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.EditText;
import android.widget.LinearLayout;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.itinerarybuddy.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class DialogCreateGroupBinding implements ViewBinding {
  @NonNull
  private final LinearLayout rootView;

  @NonNull
  public final EditText groupDescriptionInput;

  @NonNull
  public final EditText groupDestinationInput;

  @NonNull
  public final EditText groupNameInput;

  private DialogCreateGroupBinding(@NonNull LinearLayout rootView,
      @NonNull EditText groupDescriptionInput, @NonNull EditText groupDestinationInput,
      @NonNull EditText groupNameInput) {
    this.rootView = rootView;
    this.groupDescriptionInput = groupDescriptionInput;
    this.groupDestinationInput = groupDestinationInput;
    this.groupNameInput = groupNameInput;
  }

  @Override
  @NonNull
  public LinearLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static DialogCreateGroupBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static DialogCreateGroupBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.dialog_create_group, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static DialogCreateGroupBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.group_description_input;
      EditText groupDescriptionInput = ViewBindings.findChildViewById(rootView, id);
      if (groupDescriptionInput == null) {
        break missingId;
      }

      id = R.id.group_destination_input;
      EditText groupDestinationInput = ViewBindings.findChildViewById(rootView, id);
      if (groupDestinationInput == null) {
        break missingId;
      }

      id = R.id.group_name_input;
      EditText groupNameInput = ViewBindings.findChildViewById(rootView, id);
      if (groupNameInput == null) {
        break missingId;
      }

      return new DialogCreateGroupBinding((LinearLayout) rootView, groupDescriptionInput,
          groupDestinationInput, groupNameInput);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
