// Generated by view binder compiler. Do not edit!
package com.example.itinerarybuddy.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageButton;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.itinerarybuddy.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class FragmentGroupPageBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final ImageButton backButton;

  @NonNull
  public final ImageButton chatButton;

  @NonNull
  public final TextView groupDescription;

  @NonNull
  public final TextView groupDescriptionTitle;

  @NonNull
  public final TextView groupDestination;

  @NonNull
  public final TextView groupTitle;

  @NonNull
  public final ImageButton optionsButton;

  @NonNull
  public final View view;

  private FragmentGroupPageBinding(@NonNull ConstraintLayout rootView,
      @NonNull ImageButton backButton, @NonNull ImageButton chatButton,
      @NonNull TextView groupDescription, @NonNull TextView groupDescriptionTitle,
      @NonNull TextView groupDestination, @NonNull TextView groupTitle,
      @NonNull ImageButton optionsButton, @NonNull View view) {
    this.rootView = rootView;
    this.backButton = backButton;
    this.chatButton = chatButton;
    this.groupDescription = groupDescription;
    this.groupDescriptionTitle = groupDescriptionTitle;
    this.groupDestination = groupDestination;
    this.groupTitle = groupTitle;
    this.optionsButton = optionsButton;
    this.view = view;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static FragmentGroupPageBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static FragmentGroupPageBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.fragment_group_page, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static FragmentGroupPageBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.back_button;
      ImageButton backButton = ViewBindings.findChildViewById(rootView, id);
      if (backButton == null) {
        break missingId;
      }

      id = R.id.chat_button;
      ImageButton chatButton = ViewBindings.findChildViewById(rootView, id);
      if (chatButton == null) {
        break missingId;
      }

      id = R.id.group_description;
      TextView groupDescription = ViewBindings.findChildViewById(rootView, id);
      if (groupDescription == null) {
        break missingId;
      }

      id = R.id.group_description_title;
      TextView groupDescriptionTitle = ViewBindings.findChildViewById(rootView, id);
      if (groupDescriptionTitle == null) {
        break missingId;
      }

      id = R.id.group_destination;
      TextView groupDestination = ViewBindings.findChildViewById(rootView, id);
      if (groupDestination == null) {
        break missingId;
      }

      id = R.id.group_title;
      TextView groupTitle = ViewBindings.findChildViewById(rootView, id);
      if (groupTitle == null) {
        break missingId;
      }

      id = R.id.options_button;
      ImageButton optionsButton = ViewBindings.findChildViewById(rootView, id);
      if (optionsButton == null) {
        break missingId;
      }

      id = R.id.view;
      View view = ViewBindings.findChildViewById(rootView, id);
      if (view == null) {
        break missingId;
      }

      return new FragmentGroupPageBinding((ConstraintLayout) rootView, backButton, chatButton,
          groupDescription, groupDescriptionTitle, groupDestination, groupTitle, optionsButton,
          view);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
