// Generated by view binder compiler. Do not edit!
package com.example.itinerarybuddy.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageButton;
import android.widget.ListView;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.itinerarybuddy.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class FragmentGroupListBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final ImageButton addGroupButton;

  @NonNull
  public final TextView addGroupText;

  @NonNull
  public final ImageButton backButton;

  @NonNull
  public final ImageButton createGroupButton;

  @NonNull
  public final TextView createGroupLabel;

  @NonNull
  public final ListView groupList;

  @NonNull
  public final TextView groupsDescription;

  @NonNull
  public final TextView groupsListTitle;

  @NonNull
  public final View view;

  private FragmentGroupListBinding(@NonNull ConstraintLayout rootView,
      @NonNull ImageButton addGroupButton, @NonNull TextView addGroupText,
      @NonNull ImageButton backButton, @NonNull ImageButton createGroupButton,
      @NonNull TextView createGroupLabel, @NonNull ListView groupList,
      @NonNull TextView groupsDescription, @NonNull TextView groupsListTitle, @NonNull View view) {
    this.rootView = rootView;
    this.addGroupButton = addGroupButton;
    this.addGroupText = addGroupText;
    this.backButton = backButton;
    this.createGroupButton = createGroupButton;
    this.createGroupLabel = createGroupLabel;
    this.groupList = groupList;
    this.groupsDescription = groupsDescription;
    this.groupsListTitle = groupsListTitle;
    this.view = view;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static FragmentGroupListBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static FragmentGroupListBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.fragment_group_list, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static FragmentGroupListBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.add_group_button;
      ImageButton addGroupButton = ViewBindings.findChildViewById(rootView, id);
      if (addGroupButton == null) {
        break missingId;
      }

      id = R.id.add_group_text;
      TextView addGroupText = ViewBindings.findChildViewById(rootView, id);
      if (addGroupText == null) {
        break missingId;
      }

      id = R.id.back_button;
      ImageButton backButton = ViewBindings.findChildViewById(rootView, id);
      if (backButton == null) {
        break missingId;
      }

      id = R.id.create_group_button;
      ImageButton createGroupButton = ViewBindings.findChildViewById(rootView, id);
      if (createGroupButton == null) {
        break missingId;
      }

      id = R.id.create_group_label;
      TextView createGroupLabel = ViewBindings.findChildViewById(rootView, id);
      if (createGroupLabel == null) {
        break missingId;
      }

      id = R.id.group_list;
      ListView groupList = ViewBindings.findChildViewById(rootView, id);
      if (groupList == null) {
        break missingId;
      }

      id = R.id.groups_description;
      TextView groupsDescription = ViewBindings.findChildViewById(rootView, id);
      if (groupsDescription == null) {
        break missingId;
      }

      id = R.id.groups_list_title;
      TextView groupsListTitle = ViewBindings.findChildViewById(rootView, id);
      if (groupsListTitle == null) {
        break missingId;
      }

      id = R.id.view;
      View view = ViewBindings.findChildViewById(rootView, id);
      if (view == null) {
        break missingId;
      }

      return new FragmentGroupListBinding((ConstraintLayout) rootView, addGroupButton, addGroupText,
          backButton, createGroupButton, createGroupLabel, groupList, groupsDescription,
          groupsListTitle, view);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
