// Generated by view binder compiler. Do not edit!
package com.example.itinerarybuddy.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.EditText;
import android.widget.ImageButton;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.ListView;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.itinerarybuddy.R;
import com.google.android.material.floatingactionbutton.FloatingActionButton;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class FragmentHomeBinding implements ViewBinding {
  @NonNull
  private final LinearLayout rootView;

  @NonNull
  public final FloatingActionButton addItinerary;

  @NonNull
  public final Button button2;

  @NonNull
  public final EditText editTextNumber;

  @NonNull
  public final ConstraintLayout frameLayout;

  @NonNull
  public final ImageButton groupButton;

  @NonNull
  public final ImageView imageViewPersonal;

  @NonNull
  public final ListView listViewItineraries;

  @NonNull
  public final TextView textHome;

  @NonNull
  public final TextView textView;

  @NonNull
  public final TextView textView2;

  @NonNull
  public final TextView textView3;

  @NonNull
  public final TextView textView5;

  private FragmentHomeBinding(@NonNull LinearLayout rootView,
      @NonNull FloatingActionButton addItinerary, @NonNull Button button2,
      @NonNull EditText editTextNumber, @NonNull ConstraintLayout frameLayout,
      @NonNull ImageButton groupButton, @NonNull ImageView imageViewPersonal,
      @NonNull ListView listViewItineraries, @NonNull TextView textHome, @NonNull TextView textView,
      @NonNull TextView textView2, @NonNull TextView textView3, @NonNull TextView textView5) {
    this.rootView = rootView;
    this.addItinerary = addItinerary;
    this.button2 = button2;
    this.editTextNumber = editTextNumber;
    this.frameLayout = frameLayout;
    this.groupButton = groupButton;
    this.imageViewPersonal = imageViewPersonal;
    this.listViewItineraries = listViewItineraries;
    this.textHome = textHome;
    this.textView = textView;
    this.textView2 = textView2;
    this.textView3 = textView3;
    this.textView5 = textView5;
  }

  @Override
  @NonNull
  public LinearLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static FragmentHomeBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static FragmentHomeBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.fragment_home, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static FragmentHomeBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.addItinerary;
      FloatingActionButton addItinerary = ViewBindings.findChildViewById(rootView, id);
      if (addItinerary == null) {
        break missingId;
      }

      id = R.id.button2;
      Button button2 = ViewBindings.findChildViewById(rootView, id);
      if (button2 == null) {
        break missingId;
      }

      id = R.id.editTextNumber;
      EditText editTextNumber = ViewBindings.findChildViewById(rootView, id);
      if (editTextNumber == null) {
        break missingId;
      }

      id = R.id.frameLayout;
      ConstraintLayout frameLayout = ViewBindings.findChildViewById(rootView, id);
      if (frameLayout == null) {
        break missingId;
      }

      id = R.id.group_button;
      ImageButton groupButton = ViewBindings.findChildViewById(rootView, id);
      if (groupButton == null) {
        break missingId;
      }

      id = R.id.imageViewPersonal;
      ImageView imageViewPersonal = ViewBindings.findChildViewById(rootView, id);
      if (imageViewPersonal == null) {
        break missingId;
      }

      id = R.id.listViewItineraries;
      ListView listViewItineraries = ViewBindings.findChildViewById(rootView, id);
      if (listViewItineraries == null) {
        break missingId;
      }

      id = R.id.textHome;
      TextView textHome = ViewBindings.findChildViewById(rootView, id);
      if (textHome == null) {
        break missingId;
      }

      id = R.id.textView;
      TextView textView = ViewBindings.findChildViewById(rootView, id);
      if (textView == null) {
        break missingId;
      }

      id = R.id.textView2;
      TextView textView2 = ViewBindings.findChildViewById(rootView, id);
      if (textView2 == null) {
        break missingId;
      }

      id = R.id.textView3;
      TextView textView3 = ViewBindings.findChildViewById(rootView, id);
      if (textView3 == null) {
        break missingId;
      }

      id = R.id.textView5;
      TextView textView5 = ViewBindings.findChildViewById(rootView, id);
      if (textView5 == null) {
        break missingId;
      }

      return new FragmentHomeBinding((LinearLayout) rootView, addItinerary, button2, editTextNumber,
          frameLayout, groupButton, imageViewPersonal, listViewItineraries, textHome, textView,
          textView2, textView3, textView5);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
