// Generated by view binder compiler. Do not edit!
package com.example.itinerarybuddy.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.cardview.widget.CardView;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.itinerarybuddy.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ItemDayCardBinding implements ViewBinding {
  @NonNull
  private final CardView rootView;

  @NonNull
  public final TextView textViewDayContent;

  @NonNull
  public final TextView textViewDayTitle;

  private ItemDayCardBinding(@NonNull CardView rootView, @NonNull TextView textViewDayContent,
      @NonNull TextView textViewDayTitle) {
    this.rootView = rootView;
    this.textViewDayContent = textViewDayContent;
    this.textViewDayTitle = textViewDayTitle;
  }

  @Override
  @NonNull
  public CardView getRoot() {
    return rootView;
  }

  @NonNull
  public static ItemDayCardBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ItemDayCardBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.item_day_card, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ItemDayCardBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.textViewDayContent;
      TextView textViewDayContent = ViewBindings.findChildViewById(rootView, id);
      if (textViewDayContent == null) {
        break missingId;
      }

      id = R.id.textViewDayTitle;
      TextView textViewDayTitle = ViewBindings.findChildViewById(rootView, id);
      if (textViewDayTitle == null) {
        break missingId;
      }

      return new ItemDayCardBinding((CardView) rootView, textViewDayContent, textViewDayTitle);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
