// Generated by view binder compiler. Do not edit!
package com.example.itinerarybuddy.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.itinerarybuddy.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ListItemLayoutBinding implements ViewBinding {
  @NonNull
  private final LinearLayout rootView;

  @NonNull
  public final ImageView iconPopUp;

  @NonNull
  public final TextView textViewItinerary;

  private ListItemLayoutBinding(@NonNull LinearLayout rootView, @NonNull ImageView iconPopUp,
      @NonNull TextView textViewItinerary) {
    this.rootView = rootView;
    this.iconPopUp = iconPopUp;
    this.textViewItinerary = textViewItinerary;
  }

  @Override
  @NonNull
  public LinearLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ListItemLayoutBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ListItemLayoutBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.list_item_layout, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ListItemLayoutBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.iconPopUp;
      ImageView iconPopUp = ViewBindings.findChildViewById(rootView, id);
      if (iconPopUp == null) {
        break missingId;
      }

      id = R.id.textViewItinerary;
      TextView textViewItinerary = ViewBindings.findChildViewById(rootView, id);
      if (textViewItinerary == null) {
        break missingId;
      }

      return new ListItemLayoutBinding((LinearLayout) rootView, iconPopUp, textViewItinerary);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
