// Generated by view binder compiler. Do not edit!
package com.example.itinerarybuddy.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.EditText;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.itinerarybuddy.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class LoginActivityBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final Button createAccountButton;

  @NonNull
  public final View gradient;

  @NonNull
  public final Button loginButton;

  @NonNull
  public final TextView newUserText;

  @NonNull
  public final EditText passwordInput;

  @NonNull
  public final TextView passwordText;

  @NonNull
  public final TextView title;

  @NonNull
  public final EditText usernameInput;

  @NonNull
  public final TextView usernameText;

  private LoginActivityBinding(@NonNull ConstraintLayout rootView,
      @NonNull Button createAccountButton, @NonNull View gradient, @NonNull Button loginButton,
      @NonNull TextView newUserText, @NonNull EditText passwordInput,
      @NonNull TextView passwordText, @NonNull TextView title, @NonNull EditText usernameInput,
      @NonNull TextView usernameText) {
    this.rootView = rootView;
    this.createAccountButton = createAccountButton;
    this.gradient = gradient;
    this.loginButton = loginButton;
    this.newUserText = newUserText;
    this.passwordInput = passwordInput;
    this.passwordText = passwordText;
    this.title = title;
    this.usernameInput = usernameInput;
    this.usernameText = usernameText;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static LoginActivityBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static LoginActivityBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.login_activity, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static LoginActivityBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.create_account_button;
      Button createAccountButton = ViewBindings.findChildViewById(rootView, id);
      if (createAccountButton == null) {
        break missingId;
      }

      id = R.id.gradient;
      View gradient = ViewBindings.findChildViewById(rootView, id);
      if (gradient == null) {
        break missingId;
      }

      id = R.id.login_button;
      Button loginButton = ViewBindings.findChildViewById(rootView, id);
      if (loginButton == null) {
        break missingId;
      }

      id = R.id.new_user_text;
      TextView newUserText = ViewBindings.findChildViewById(rootView, id);
      if (newUserText == null) {
        break missingId;
      }

      id = R.id.password_input;
      EditText passwordInput = ViewBindings.findChildViewById(rootView, id);
      if (passwordInput == null) {
        break missingId;
      }

      id = R.id.password_text;
      TextView passwordText = ViewBindings.findChildViewById(rootView, id);
      if (passwordText == null) {
        break missingId;
      }

      id = R.id.title;
      TextView title = ViewBindings.findChildViewById(rootView, id);
      if (title == null) {
        break missingId;
      }

      id = R.id.username_input;
      EditText usernameInput = ViewBindings.findChildViewById(rootView, id);
      if (usernameInput == null) {
        break missingId;
      }

      id = R.id.username_text;
      TextView usernameText = ViewBindings.findChildViewById(rootView, id);
      if (usernameText == null) {
        break missingId;
      }

      return new LoginActivityBinding((ConstraintLayout) rootView, createAccountButton, gradient,
          loginButton, newUserText, passwordInput, passwordText, title, usernameInput,
          usernameText);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
